name: Deploy Aqua

on: 
  workflow_dispatch:
    inputs: true
      version: 
        description: Version to be deployed
        required: true

jobs:
  deploy:
    name: Deploy documentation
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: |
          pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
          pip install mike
          pip install mkdocs-macros-plugin
        env:
          # Note: It is not the same as ${{ secrets.GITHUB_TOKEN }} !
          GH_TOKEN: ${{ secrets.MKDOCS_AQUA_BOT }}
      - run: |
          git config user.name "bot"
          git config user.email "aqua-bot@users.noreply.github.com"
      - run: |
          mike deploy --push --update-aliases ${{ github.event.inputs.version }} latest
