steps:
  - name: Authenticate and set context
    uses: redhat-actions/oc-login@v1
    env:
      # These can be stored in secrets, if desired.
      OPENSHIFT_USER: kamarules
      OPENSHIFT_NAMESPACE: false
      openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}

      # Authentication Token. Can use username and password instead.
      # Refer to Step 3.
      openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}

      # Credentials, if desired instead of token.
      # Username and password override token if they are set.
      openshift_username: ${{ env.OPENSHIFT_USER }}
      openshift_password: ${{ secrets.OPENSHIFT_PASSWORD }}

      # Disables SSL cert checking. Use this if you don't have the certificate authority data.
      insecure_skip_tls_verify: true
      # This method is more secure, if the certificate from Step 4 is available.
      certificate_authority_data: ${{ secrets.CA_DATA }}

      # Optional - this sets your Kubernetes context's current namespace after logging in.
      namespace: ${{ env.OPENSHIFT_NAMESPACE }}
